### ISSUE TITLE
No direct link to help article and search results

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/veracode-api#6]
For example I'm opening an issue which I would like to point to a search result and an article (see pics below)

At the moment the only link that looks available is the https://analysiscenter.veracode.com/auth/index.jsp?subsystem=helpcenter

![image](https://cloud.githubusercontent.com/assets/656739/18704527/24dadda6-7fe2-11e6-97f7-928b34ff1b12.png)

![image](https://cloud.githubusercontent.com/assets/656739/18704577/63dec7f6-7fe2-11e6-8b5e-1ac566d58911.png)

Note: one workaround is to open the article in a separate tab and copy that link (for example https://analysiscenter.veracode.com/auth/helpCenter/policy/policy_veracodelevel.html )

![image](https://cloud.githubusercontent.com/assets/656739/18704613/8d2aa21a-7fe2-11e6-8159-a709086e4caf.png)

**Comment by tjarrettveracode** [comment]
This isn't as easy as it should be. You can get a direct link to an article page by right clicking a link that points to it, either on the up-level page or in search results.

**Comment by DinisCruz** [comment]
yeah, that is what I thought (at least I know I'm not missing something obvious)

**Comment by DinisCruz** [comment]
@veracode answer:
_This is a known problem and our Engineering team is looking for a long-term solution with an overhaul of the Help Center. In the meantime, you can get the URL for a Help Center page by right-clicking a result that links to it and selecting "Copy Link Address" (or the appropriate alternative depending on the browser you're using)._
