### ISSUE TITLE
Question: Does the Veracode level affect the coverage of static scan

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/veracode-api#7]
Looking at https://analysiscenter.veracode.com/auth/helpCenter/policy/policy_veracodelevel.html is it not that clear if the scanning rules (and techniques) are dependent on the chosen veracode level.

Namely will there be any difference in the results if I chose 

![image](https://cloud.githubusercontent.com/assets/656739/18704693/f01f20bc-7fe2-11e6-85f4-c52bfd3c64be.png)

vs

![image](https://cloud.githubusercontent.com/assets/656739/18704700/f7c87020-7fe2-11e6-9b93-07e519ff90c2.png)

**Comment by tjarrettveracode** [comment]
No, this has no effect on the scanning rules and techniques. You can think about the policy applied to the application as a filter that highlights findings that violate the selected policy rules. 

The engine is smart enough to apply different rules and techniques to applications based on the characteristics of the code (e.g. assuming web-based tainting where appropriate, automatically invoking control flow transformations based on the frameworks in use).

**Comment by DinisCruz** [comment]
great thanks

**Comment by DinisCruz** [comment]
Further answer from @veracode support: 

_Veracode Level/Policy have no impact on the scan itself, they merely act as a lens through which the results are viewed for security compliance. Here are a few links to the Help Center with more information on them:
https://analysiscenter.veracode.com/auth/helpCenter/policy/policy_understand.html
https://analysiscenter.veracode.com/auth/helpCenter/policy/policy_veracodelevel.html_
